#Provide declarative updates for replicaSets and Pods
#k8s compares the actual state with the desired state. them, the deployment control updates the state, if needed

###Use Cases:
  #Rollout a Replica set
  #Declare a new pod state
  #Rollback to an earlier deployment version
  #Scale up to support more load
  #pause a rollout
  #Clean up old replica sets

#After finish, the deployent status may be consulted to ensure it worked or not

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels: 
    app: nginx
spec:
  progressDeadlineSeconds: 600 ##Make the controller report lack of progress in the deploy after 10 minutes
  replicas: 3 ##number of pods
  selector: ##Defines the pod the deployment will search for
####!!!!!COUTION: do not overlap selectors!!!!!
    matchLabels:
      app: nginx
  template: ##Countains the pod specs
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

##Deployments garantee uptime when updating the pods. The new ones will be created and them the old ones are removed
##It`s not good to update the selector! (in some api versions it's even immutable)

##Rollouts and rollbacks are stored in deployment history, making ease to switch between versions
##check for specific commands in https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

##Scaling up and down can be made through spec.replicas prop. It will create the desired number of replica sets

##Autoscaling can be done by the command:
# kubectl autoscale deployment/nginx-deployment --min=10 --max=15 --cpu-percent=80

####DEPLOYMENT LIFECYLCE
#Creates new replica sets
#Scale up the newest RS
#Scale down the old RS
#New pods get read or available

###Reasons for failure on deployment
# Insuficcient quota
# Readiness probe failure
# Image pull error
# Insuficient permissions
# Limit Ranges
# Application misconfig
