apiVersion: v1
kind: Pod
metadata:
  name: Job
  labels:
    name: Job
spec:
  containers:
  - name: Job
    image: scratch
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
