##Contains small amount of sensitive data
#Secrets are INDEPENDENT of the used pod
##Secrets are stored on K8s API in an encrypted way. thats why they are more secure
##On the secrets.yaml file, secrets are stored in base64. Since it's not safe, it's not recommended to save such files
##Secrets can also be stored inside a volume (to be used by a pod)
##Secrets can be marked to be optional. the default value is required, although
##Multiple pods can reference the same secret

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: RG9Ob3RVc2VhYmNAMTIz
